name: Mirror Maven Artifact

on:
  workflow_dispatch:
    inputs:
      group_id:
        description: 'Group ID (e.g. org.apache.commons)'
        required: true
      artifact_id:
        description: 'Artifact ID (e.g. commons-lang3)'
        required: true
      version:
        description: 'Version (e.g. 3.14.0)'
        required: true

jobs:
  mirror-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Use repository-stored settings.xml
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>\${env.MAVEN_USERNAME}</username>
              <password>\${env.MAVEN_PASSWORD}</password>
            </server>
          </servers>
          <mirrors>
            <mirror>
              <id>github</id>
              <url>https://maven.pkg.github.com/Shalini-source/mob-backend-lib</url>
              <mirrorOf>central</mirrorOf>
            </mirror>
          </mirrors>
        </settings>
        EOF

    - name: Create download directory
      run: mkdir -p ./artifact

    - name: Download JAR from Maven Central
      run: |
        mvn dependency:copy \
          -Dartifact=${{ github.event.inputs.group_id }}:${{ github.event.inputs.artifact_id }}:${{ github.event.inputs.version }} \
          -DoutputDirectory=./artifact
        mvn dependency:copy \
          -Dartifact=${{ github.event.inputs.group_id }}:${{ github.event.inputs.artifact_id }}:${{ github.event.inputs.version }}:pom \
          -DoutputDirectory=./artifact


    - name: Locate downloaded JAR
      id: locate_jar
      run: |
        JAR_NAME="${{ github.event.inputs.artifact_id }}-${{ github.event.inputs.version }}.jar"
        echo "jar_name=$JAR_NAME" >> $GITHUB_OUTPUT
        
    - name: Verify downloaded file exists
      run: ls -lh ./artifact

    - name: Deploy to GitHub Packages
      run: |
        mvn deploy:deploy-file \
          -DgroupId=${{ github.event.inputs.group_id }} \
          -DartifactId=${{ github.event.inputs.artifact_id }} \
          -Dversion=${{ github.event.inputs.version }} \
          -Dpackaging=jar \
          -Dfile=./artifact/${{ steps.locate_jar.outputs.jar_name }} \
          -DpomFile=./artifact/${{ github.event.inputs.artifact_id }}-${{ github.event.inputs.version }}.pom
          -DrepositoryId=github \
          -Durl=https://maven.pkg.github.com/Shalini-source/mob-backend-lib
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.PAT_TOKEN }}
