name: Mirror Maven Artifact

on:
  workflow_dispatch:
    inputs:
      group_id:
        description: 'Group ID (e.g. org.apache.commons)'
        required: true
      artifact_id:
        description: 'Artifact ID (e.g. commons-lang3)'
        required: true
      version:
        description: 'Version (e.g. 3.14.0)'
        required: true

jobs:
  mirror-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Use repository-stored settings.xml
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.PAT_TOKEN }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>maven-central-profile</id>
              <repositories>
                <repository>
                  <id>central</id>
                  <name>Maven Central Repository</name>
                  <url>https://repo.maven.apache.org/maven2</url>
                  <releases><enabled>true</enabled></releases>
                  <snapshots><enabled>false</enabled></snapshots>
                </repository>
              </repositories>
            </profile>
          </profiles>
        
          <activeProfiles>
            <activeProfile>maven-central-profile</activeProfile>
          </activeProfiles>
        </settings>
        EOF

    - name: Create download directory
      run: mkdir -p ./artifact

    - name: Download JAR from Maven Central
      run: |
        mvn -U dependency:copy \
          -Dartifact=${{ github.event.inputs.group_id }}:${{ github.event.inputs.artifact_id }}:${{ github.event.inputs.version }} \
          -DoutputDirectory=./artifact
        mvn -U dependency:copy \
          -Dartifact=${{ github.event.inputs.group_id }}:${{ github.event.inputs.artifact_id }}:${{ github.event.inputs.version }}:pom \
          -DoutputDirectory=./artifact


    - name: Locate downloaded JAR
      id: locate_jar
      run: |
        JAR_NAME="${{ github.event.inputs.artifact_id }}-${{ github.event.inputs.version }}.jar"
        echo "jar_name=$JAR_NAME" >> $GITHUB_OUTPUT
        POM_NAME="${{ github.event.inputs.artifact_id }}-${{ github.event.inputs.version }}.pom"
        echo "pom_name=$POM_NAME"
        
    - name: Verify downloaded file exists
      run: ls -lh ./artifact

    - name: Deploy to GitHub Packages
      run: |
        JAR_NAME="${{ github.event.inputs.artifact_id }}-${{ github.event.inputs.version }}.jar"
        POM_NAME="${{ github.event.inputs.artifact_id }}-${{ github.event.inputs.version }}.pom"
    
        mvn -U deploy:deploy-file \
          -DgroupId=${{ github.event.inputs.group_id }} \
          -DartifactId=${{ github.event.inputs.artifact_id }} \
          -Dversion=${{ github.event.inputs.version }} \
          -Dpackaging=jar \
          -Dfile=./artifact/$JAR_NAME \
          -DpomFile=./artifact/$POM_NAME \
          -DrepositoryId=github \
          -Durl=https://maven.pkg.github.com/Shalini-source/mob-backend-lib \
          -DgeneratePom=false
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.PAT_TOKEN }}
