name: Build and Publish Spring Config

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <mirrors>
              <mirror>
                <id>central</id>
                <name>Maven Central Mirror</name>
                <url>https://repo.maven.apache.org/maven2</url>
                <mirrorOf>central</mirrorOf>
              </mirror>
            </mirrors>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.PAT_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and Deploy
        run: mvn clean deploy
        
